apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ct308-gph001-vgph001-df-generator
  namespace: ct308-gph001-vgph001-v1-df
  labels:
    app: ct308-gph001-vgph001-df-generator
spec:
  replicas: 1
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 30s
        - setWeight: 50
        - pause:
            duration: 60s
        - setWeight: 100
  selector:
    matchLabels:
      app: ct308-gph001-vgph001-df-generator
  template:
    metadata:
      labels:
        app: ct308-gph001-vgph001-df-generator
    spec:
      containers:
        - name: ct308-gph001-vgph001-df-generator-backend
          image: 192.168.2.164:5000/ct308-gph001-vgph001-df-v1:docker_tag
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: redis_host
              value: "192.168.2.180"
            - name: redis_port
              value: "32055"

---
apiVersion: v1
kind: Service
metadata:
  name: ct308-gph001-vgph001-df-generator
  namespace: ct308-gph001-vgph001-v1-df
  labels:
    app: ct308-gph001-vgph001-df-generator
spec:
  selector:
    app: ct308-gph001-vgph001-df-generator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 3000
  type: ClusterIP
